# 24. 예외 처리(try catch) 문법 & 응용

```java
public class Exception {
    public static void main(String[] args) {
        int a, b, c;
        try {
            a = 10;
            b = 0;
            c = a / b; // 10 나누기 0 → 산술오류 ArithmeticException
        } catch (ArithmeticException e) {
            c = -1;  // 예외가 발생하여 이 문장이 수행된다.
        }
    }
}
```

```java
public class Exception {
    public static void main(String[] args) {
        int a, b, c;
        try {
	        	a = 10;
            b = 0;
            c = a / b;
            
        } catch (NumberFormatException e) {
            System.out.println("숫자로 변환할 수 없습니다.");
        } catch (ClassNotFoundException e) {
            System.out.println("클래스가 존재하지 않습니다.");         
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("실행 매개값의 수가 부족합니다.");
        } catch (IOException e) {
            System.out.println("입력값이 잘못 되었습니다.");
        } catch (NullPointException e) {
            System.out.println("NULL을 참조하고 있습니다.");
        } ...
    }
}
```

```java
// 사용자 커스텀 예외 클래스를 만들려면 부모 클래스인 Exception 클래스를 상속 하면 된다.
class MyErrException extends Exception {
    private String msg;
	
    // 사용자 커스텀 예외클래스 생성자
    public MyErrException(String msg) {
        super(msg); // 부모 Exception 클래스 생성자도 호출
        this.msg = msg;
    }
	
    // 사용자 커스텀 예외클래스 메세지 출력
    public void printMyMessage() {
        System.out.println(this.msg);
    }
}

public class Main {
    public static void main(String[] args) {
        try {
            throw new MyErrException("나의 커스텀 예외 클래스 메세지"); // 커스텀 예외 클래스 발생
        } catch (MyErrException e) {
            e.printMyMessage(); // 커스텀 예외 클래스의 메서드 실행
            e.printStackTrace(); // 상속한 부모클래스의 메서드 실행
        }
    }
}
```